BEGIN TRANSACTION;
CREATE TABLE mod_advice_infos (id INTEGER PRIMARY KEY, name TEXT UNIQUE, regex TEXT UNIQUE, color TEXT DEFAULT 'teal');
INSERT INTO "mod_advice_infos" VALUES(1,'Courage Wolf','couragewolf','red');
INSERT INTO "mod_advice_infos" VALUES(2,'Philosoraptor','philosoraptor','green');
INSERT INTO "mod_advice_infos" VALUES(3,'Depression dog','depressiondog','dark_gray');
INSERT INTO "mod_advice_infos" VALUES(4,'Socially Awkward Penguin','awkwardpenguin','royal_blue');
INSERT INTO "mod_advice_infos" VALUES(5,'Political Neutral Dog','politicalneutraldog','hot_pink');
INSERT INTO "mod_advice_infos" VALUES(6,'Wisdom Cat','wisdomcat','yellow');
INSERT INTO "mod_advice_infos" VALUES(7,'Spoiler Dog','spoilerdog','teal');
INSERT INTO "mod_advice_infos" VALUES(8,'Technologically Impaired Duck','technologicallyimpairedduck','orange');
CREATE TABLE mod_advice_advices (id INTEGER PRIMARY KEY, typeId INTEGER, advice TEXT UNIQUE, infoId INTEGER REFERENCES mod_advice_infos (id));
INSERT INTO "mod_advice_advices" VALUES(1,1,'Pain is temporary, Glory is eternal',1);
INSERT INTO "mod_advice_advices" VALUES(2,1,'A man with one watch knows what time it is, a man with two watches is never quite sure',2);
INSERT INTO "mod_advice_advices" VALUES(3,2,'Fear is instinct, Courage is choice',1);
INSERT INTO "mod_advice_advices" VALUES(4,3,'When you reach the gates of Heaven, Kick the gates open',1);
INSERT INTO "mod_advice_advices" VALUES(5,4,'There is no failure, only postponed success',1);
INSERT INTO "mod_advice_advices" VALUES(6,5,'Elevator to greatness is out of order. Fuck it, i''ll take stairs.',1);
INSERT INTO "mod_advice_advices" VALUES(7,6,'One day as a Wolf beats 100 years as a Sheep',1);
INSERT INTO "mod_advice_advices" VALUES(8,7,'Seize the day, By the throat',1);
INSERT INTO "mod_advice_advices" VALUES(9,8,'Climb the highest mountain, Punch the face of God',1);
INSERT INTO "mod_advice_advices" VALUES(10,9,'Show no mercy, For you shall recieve none',1);
INSERT INTO "mod_advice_advices" VALUES(11,10,'Kill them all, Live forever',1);
INSERT INTO "mod_advice_advices" VALUES(12,11,'Never sleep, rest when you die',1);
INSERT INTO "mod_advice_advices" VALUES(13,12,'Kill one, Terrify a thousand',1);
INSERT INTO "mod_advice_advices" VALUES(14,13,'Eat lightning, Shit thunder',1);
INSERT INTO "mod_advice_advices" VALUES(15,14,'Fear is a reflex, Confidence is a choice',1);
INSERT INTO "mod_advice_advices" VALUES(16,15,'Winning is my habit, What is yours ?',1);
INSERT INTO "mod_advice_advices" VALUES(17,16,'God hates winners, Be your own God',1);
INSERT INTO "mod_advice_advices" VALUES(18,17,'Awesome is a synonym for YOU',1);
INSERT INTO "mod_advice_advices" VALUES(19,18,'Better to reign in Hell than server in Heaven',1);
INSERT INTO "mod_advice_advices" VALUES(20,19,'Kill the weak, Use them for fires',1);
INSERT INTO "mod_advice_advices" VALUES(21,20,'He might be good, but you are better',1);
INSERT INTO "mod_advice_advices" VALUES(22,21,'Lightning never strikes twice, unless you hit him AGAIN',1);
INSERT INTO "mod_advice_advices" VALUES(23,22,'Don''t dodge, Counter !',1);
INSERT INTO "mod_advice_advices" VALUES(24,23,'Fear is nothing but the inability to stare pure power in the face',1);
INSERT INTO "mod_advice_advices" VALUES(25,24,'Why question yourself when you already have the answer ?',1);
INSERT INTO "mod_advice_advices" VALUES(26,25,'You tried to beat me, Tried being the operative word',1);
INSERT INTO "mod_advice_advices" VALUES(27,26,'If you dont live for something, you will die for nothing',1);
INSERT INTO "mod_advice_advices" VALUES(28,27,'Never apologize For being right',1);
INSERT INTO "mod_advice_advices" VALUES(29,28,'Reach the finish line, Keep going',1);
INSERT INTO "mod_advice_advices" VALUES(30,29,'Rise today, Change the world',1);
INSERT INTO "mod_advice_advices" VALUES(31,30,'Courage can be a VERB',1);
INSERT INTO "mod_advice_advices" VALUES(32,31,'When I am, Death is not. When Death is, I am not. Why should i fear someting that cannot exist while I do ?',1);
INSERT INTO "mod_advice_advices" VALUES(33,32,'Shoot tax collectors, they didnt earn your money',1);
INSERT INTO "mod_advice_advices" VALUES(34,33,'Don''t just beat them, Annihilate them!',1);
INSERT INTO "mod_advice_advices" VALUES(35,34,'Turn your fist into a hammer of courage, they wont last long',1);
INSERT INTO "mod_advice_advices" VALUES(36,35,'When you reach Hell, Punch Satan tell him I SENT YOU',1);
INSERT INTO "mod_advice_advices" VALUES(37,36,'Hit back hard, and without mercy, they''ll stop',1);
INSERT INTO "mod_advice_advices" VALUES(38,37,'The only true failure is accepting failure',1);
INSERT INTO "mod_advice_advices" VALUES(39,38,'Fall seven times, stand up eight',1);
INSERT INTO "mod_advice_advices" VALUES(40,39,'Die on you feet, or live on your knees',1);
INSERT INTO "mod_advice_advices" VALUES(41,40,'If you''re not going to pull the trigger, don''t point the gun',1);
INSERT INTO "mod_advice_advices" VALUES(42,41,'They judge you with their eyes, Judge them with your fists',1);
INSERT INTO "mod_advice_advices" VALUES(43,42,'It''s not a matter of who is going to LET me, it''s a question of who is going to STOP me',1);
INSERT INTO "mod_advice_advices" VALUES(44,43,'Blood looks better, on the outside',1);
INSERT INTO "mod_advice_advices" VALUES(45,44,'Nothing to lose means nothing but gain',1);
INSERT INTO "mod_advice_advices" VALUES(46,45,'Don''t believe in yourself. Believe in me, who believes in you.',1);
INSERT INTO "mod_advice_advices" VALUES(47,46,'You were born a winner, you were the fastest sperm',1);
INSERT INTO "mod_advice_advices" VALUES(48,47,'The doctor said it was cancer, I call it a challenge',1);
INSERT INTO "mod_advice_advices" VALUES(49,48,'You are awesome, Go and prove it',1);
INSERT INTO "mod_advice_advices" VALUES(50,49,'If life asks for your all, give it even more',1);
INSERT INTO "mod_advice_advices" VALUES(51,50,'Stop theorizing, build a prototype',1);
INSERT INTO "mod_advice_advices" VALUES(52,51,'When you were born, you made that bitch cry',1);
INSERT INTO "mod_advice_advices" VALUES(53,52,'Bite off more than you can chew, then chew it',1);
INSERT INTO "mod_advice_advices" VALUES(54,53,'An obstacle is only something you haven''t torn through yet',1);
INSERT INTO "mod_advice_advices" VALUES(55,54,'Someone ought to do something, That someone is you',1);
INSERT INTO "mod_advice_advices" VALUES(56,55,'Life sucks, then you die. Take the world with you.',1);
INSERT INTO "mod_advice_advices" VALUES(57,56,'There is do or not dot. There is no try.',1);
INSERT INTO "mod_advice_advices" VALUES(58,57,'Depression is just another way of saying "I dont want to try"',1);
INSERT INTO "mod_advice_advices" VALUES(59,58,'The best way out is through',1);
INSERT INTO "mod_advice_advices" VALUES(60,59,'Why be sly when you can tear through',1);
INSERT INTO "mod_advice_advices" VALUES(61,60,'Yours is the drill that will pierce the Heavens',1);
INSERT INTO "mod_advice_advices" VALUES(62,61,'Why fear the unknown When you can conquer it',1);
INSERT INTO "mod_advice_advices" VALUES(63,62,'You are always at FULL POWER',1);
INSERT INTO "mod_advice_advices" VALUES(64,63,'Fuck regrets, Not even your past can get in your way',1);
INSERT INTO "mod_advice_advices" VALUES(65,64,'Life fucked you, Fuck it back',1);
INSERT INTO "mod_advice_advices" VALUES(66,65,'Life is a bitch, you''re her pimp',1);
INSERT INTO "mod_advice_advices" VALUES(67,66,'Life is meaningless, Enjoy the fucking ride',1);
INSERT INTO "mod_advice_advices" VALUES(68,67,'Bring a knife to a gunfight, Stab them while they''re laughing',1);
INSERT INTO "mod_advice_advices" VALUES(69,68,'Life is a box of chocolates, Eat it',1);
INSERT INTO "mod_advice_advices" VALUES(70,69,'Even if you fall on your face, you''re still moving forward',1);
INSERT INTO "mod_advice_advices" VALUES(71,70,'When life gets you down, take it down with you',1);
INSERT INTO "mod_advice_advices" VALUES(72,71,'Why bite the hand that feeds, Take the whole damn arm',1);
INSERT INTO "mod_advice_advices" VALUES(73,72,'Never unclench your fist, unless you find a gun',1);
INSERT INTO "mod_advice_advices" VALUES(74,73,'There is no couRAGE without RAGE',1);
INSERT INTO "mod_advice_advices" VALUES(75,74,'Life is a highway, Let your tires run red with blood',1);
INSERT INTO "mod_advice_advices" VALUES(76,75,'Pretend to be their friend, Learn their weaknesses',1);
INSERT INTO "mod_advice_advices" VALUES(77,76,'Dont look for happiness, Make it find you',1);
INSERT INTO "mod_advice_advices" VALUES(78,77,'Grab the world by the balls, and squeeze like hell',1);
INSERT INTO "mod_advice_advices" VALUES(79,78,'No one remembers who came in 2nd place',1);
INSERT INTO "mod_advice_advices" VALUES(80,79,'Todays horoscope : Fuck Yeah',1);
INSERT INTO "mod_advice_advices" VALUES(81,80,'Don''t be racists, Kill everyone',1);
INSERT INTO "mod_advice_advices" VALUES(82,81,'The man got you down, Kill his fucking family',1);
INSERT INTO "mod_advice_advices" VALUES(83,82,'Hit a brick wall, go through it',1);
INSERT INTO "mod_advice_advices" VALUES(84,83,'A journey requires you to take steps',1);
INSERT INTO "mod_advice_advices" VALUES(85,84,'Infiltrate. Destroy. Rebuild.',1);
INSERT INTO "mod_advice_advices" VALUES(86,85,'Jump out your window, Fuck gravity',1);
INSERT INTO "mod_advice_advices" VALUES(87,86,'Divide by zero, Live to tell the tale',1);
INSERT INTO "mod_advice_advices" VALUES(88,87,'Depression breeds depression, Effort breeds success',1);
INSERT INTO "mod_advice_advices" VALUES(89,2,'Even a clock that does not work... Is right twice a day',2);
INSERT INTO "mod_advice_advices" VALUES(90,3,'Which came first, the advice or the dog ?',2);
INSERT INTO "mod_advice_advices" VALUES(91,4,'If I try to lose the game and succeed... do I win the game ?',2);
INSERT INTO "mod_advice_advices" VALUES(92,5,'Why doesn''t he afraid of anything',2);
INSERT INTO "mod_advice_advices" VALUES(93,6,'Is the cake... a lie ?',2);
INSERT INTO "mod_advice_advices" VALUES(94,7,'Do I exist because there is porn of me ? Or is it that because I exist, there is porn of me ?',2);
INSERT INTO "mod_advice_advices" VALUES(95,1,'Put your booksack in the seat next to you, No one will sit there anyway',3);
INSERT INTO "mod_advice_advices" VALUES(96,2,'Sleep holding pillow, It will not reject you',3);
INSERT INTO "mod_advice_advices" VALUES(97,3,'Holw own hand, Friends will not notice',3);
INSERT INTO "mod_advice_advices" VALUES(98,4,'Hug sister, imagine girlfriend',3);
INSERT INTO "mod_advice_advices" VALUES(99,5,'Cry in the dark, Nobody wants to see you',3);
INSERT INTO "mod_advice_advices" VALUES(100,6,'This year''s birthday was the best. I had the cake all to myself.',3);
INSERT INTO "mod_advice_advices" VALUES(101,7,'Say "I''m fine", Realise no-one asks, ever',3);
INSERT INTO "mod_advice_advices" VALUES(102,8,'Kill Yourself, They won''t notice.',3);
INSERT INTO "mod_advice_advices" VALUES(103,9,'Slit wrists, Write poetry',3);
INSERT INTO "mod_advice_advices" VALUES(104,10,'Drink ammonia, Cry alone as you die',3);
INSERT INTO "mod_advice_advices" VALUES(105,11,'Have conversations with wrong numbers, Maybe they''ll want to be friends',3);
INSERT INTO "mod_advice_advices" VALUES(106,1,'Men and women are equally intellignet',5);
INSERT INTO "mod_advice_advices" VALUES(107,2,'There is a link between povery and crime',5);
INSERT INTO "mod_advice_advices" VALUES(108,3,'Abortion is a difficult issue',5);
INSERT INTO "mod_advice_advices" VALUES(109,4,'Everyone has a right to his/her own opinion.',5);
INSERT INTO "mod_advice_advices" VALUES(110,5,'I prefer to not specify my race',5);
INSERT INTO "mod_advice_advices" VALUES(111,1,'Wat ?!? Darth Vader is Luke''s father ?!?',7);
INSERT INTO "mod_advice_advices" VALUES(112,2,'Holy shit ! Rorschach dies !',7);
INSERT INTO "mod_advice_advices" VALUES(113,3,'Cigarettes cause CANCER ?!',7);
INSERT INTO "mod_advice_advices" VALUES(114,4,'OMG !!! People die when they''re killed',7);
INSERT INTO "mod_advice_advices" VALUES(115,1,'You check your phone, because you have nothing to contribute to the conversation',4);
INSERT INTO "mod_advice_advices" VALUES(116,2,'Start dancing, Feel weird and stop',4);
INSERT INTO "mod_advice_advices" VALUES(117,3,'Recognise friend of friend on other end of street, walking in your direction. Signal and smile stupid until proximity allows communication',4);
INSERT INTO "mod_advice_advices" VALUES(118,4,'Wait for right time to say something. Get interrupted.',4);
INSERT INTO "mod_advice_advices" VALUES(119,5,'Be polite, hold the door. They''re slightly too far away.',4);
INSERT INTO "mod_advice_advices" VALUES(120,1,'I can''t surf the internet anymore, I DELETED THE ICON',8);
INSERT INTO "mod_advice_advices" VALUES(121,2,'I''m already pressing A, HOW DO I CONTROL IT ?',8);
INSERT INTO "mod_advice_advices" VALUES(122,3,'How do i get the viruses of my computer ? Delete SYSTEM32 you say ?',8);
INSERT INTO "mod_advice_advices" VALUES(123,4,'I''ve been thinking of switching to internet explorer, the internet is free on that program',8);
INSERT INTO "mod_advice_advices" VALUES(124,5,'I''m yet to recieve my winnings from the Central Bank of Nigeria',8);
INSERT INTO "mod_advice_advices" VALUES(125,6,'I have my Modem, now where is my internet ?',8);
INSERT INTO "mod_advice_advices" VALUES(126,1,'Don''t taze him Bro !',6);
INSERT INTO "mod_advice_advices" VALUES(127,2,'Don''t run with scissors',6);
INSERT INTO "mod_advice_advices" VALUES(128,3,'Eat healthy and exercise',6);
INSERT INTO "mod_advice_advices" VALUES(129,6,'Gaze at random spot, focus and notice you''ve been looking at a man''s crotch',4);
INSERT INTO "mod_advice_advices" VALUES(130,7,'Stumble while walking, Look back at invisible object',4);
INSERT INTO "mod_advice_advices" VALUES(131,8,'Wash your hands after peeing, splash water on the front of your pants',4);
INSERT INTO "mod_advice_advices" VALUES(132,9,'You laugh at a joke but you dont get it, Someone asks you to explain it',4);
INSERT INTO "mod_advice_advices" VALUES(133,10,'You move your bag so they can sit next to you, They walk past you and sit with someone else',4);
INSERT INTO "mod_advice_advices" VALUES(134,11,'The waitress tells you to enjoy your meal, you say "You too"',4);
INSERT INTO "mod_advice_advices" VALUES(135,12,'Someone is walking towar you, a setup for collision. You move to the side, They move to the same side.',4);
INSERT INTO "mod_advice_advices" VALUES(136,13,'Wave back. She ment the person behind you. Touch head.',4);
INSERT INTO "mod_advice_advices" VALUES(137,88,'Courage without conscience is a wild beast, Be the beast',1);
INSERT INTO "mod_advice_advices" VALUES(138,89,'Yesterday i dared to struggle, Today i dare to win',1);
INSERT INTO "mod_advice_advices" VALUES(139,90,'Go ahead, be the alfa male',1);
INSERT INTO "mod_advice_advices" VALUES(140,91,'C''mon world ! Give me your best shot !',1);
CREATE TABLE mod_advice_tmp (id INTEGER PRIMARY KEY, user TEXT, channel TEXT, infoId INTEGER REFERENCES infos (id), advice TEXT UNIQUE);
INSERT INTO "mod_advice_tmp" VALUES(1,'GentilBoulet[perlmonkshaolin]','#giraf',1,'Natural selection favoers perseverance');
COMMIT;
